export const artStyles = [
    {
        label: "Ultra Realism",
        options: [
            { value: "Hyper Realistic", name: "Hyper Realistic" },
            { value: "Hyper Realm", name: "Hyper Realm" },
            { value: "8K Photorealistic", name: "8K Photorealistic" },
            { value: "Cinematic Realism", name: "Cinematic Realism" },
            { value: "Hyperdetailed", name: "Hyperdetailed" },
            { value: "Sci-Fi Realism", name: "Sci-Fi Realism" },
            { value: "Medical Illustration", name: "Medical Illustration" },
        ],
    },
    {
        label: "Specialized Techniques",
        options: [
            { value: "airbrush", name: "Airbrush Art" },
            { value: "scratchboard", name: "Scratchboard Art" },
            { value: "linocut print", name: "Linocut Print" },
            { value: "woodblock print", name: "Woodblock Print" },
            { value: "silkscreen", name: "Silkscreen Printing" },
            { value: "engraving", name: "Engraving" },
            { value: "mezzotint", name: "Mezzotint" },
            { value: "lithography", name: "Lithography" },
            { value: "etching", name: "Etching" },
            { value: "drypoint", name: "Drypoint" },
        ],
    },
    {
        label: "Contemporary Styles",
        options: [
            { value: "street art", name: "Street Art" },
            { value: "graffiti", name: "Graffiti" },
            { value: "stencil art", name: "Stencil Art" },
            { value: "pop surrealism", name: "Pop Surrealism" },
            { value: "lowbrow art", name: "Lowbrow Art" },
            { value: "urban contemporary", name: "Urban Contemporary" },
            { value: "outsider art", name: "Outsider Art" },
            { value: "naive art", name: "Naive Art" },
            { value: "folk art", name: "Folk Art" },
            { value: "visionary art", name: "Visionary Art" },
        ],
    },
    {
        label: "Digital & Mixed Media",
        options: [
            { value: "digital collage", name: "Digital Collage" },
            { value: "mixed media", name: "Mixed Media" },
            { value: "photo manipulation", name: "Photo Manipulation" },
            { value: "vector art", name: "Vector Art" },
            { value: "pixel art", name: "Pixel Art" },
            { value: "vaporwave", name: "Vaporwave Aesthetic" },
            { value: "synthwave", name: "Synthwave" },
            { value: "outrun", name: "Outrun Style" },
            { value: "cybergoth", name: "Cybergoth" },
            { value: "y2k aesthetic", name: "Y2K Aesthetic" },
        ],
    },
    {
        label: "Illustration Styles",
        options: [
            { value: "editorial illustration", name: "Editorial Illustration" },
            { value: "scientific illustration", name: "Scientific Illustration" },
            { value: "botanical illustration", name: "Botanical Illustration" },
            { value: "medical illustration", name: "Medical Illustration" },
            { value: "technical drawing", name: "Technical Drawing" },
            { value: "infographic", name: "Infographic Style" },
            { value: "comic book", name: "Comic Book Style" },
            { value: "graphic novel", name: "Graphic Novel" },
            { value: "storyboard", name: "Storyboard Style" },
            { value: "concept art", name: "Concept Art" },
        ],
    },
    {
        label: "Regional & Ethnic Styles",
        options: [
            { value: "african art", name: "African Art" },
            { value: "aboriginal art", name: "Aboriginal Art" },
            { value: "maori art", name: "Maori Art" },
            { value: "native american", name: "Native American Art" },
            { value: "aztec art", name: "Aztec Art" },
            { value: "mayan art", name: "Mayan Art" },
            { value: "inca art", name: "Inca Art" },
            { value: "balinese art", name: "Balinese Art" },
            { value: "javanese batik", name: "Javanese Batik" },
            { value: "thai art", name: "Thai Art" },
        ],
    },
    {
        label: "Photography Styles",
        options: [
            { value: "professional photography", name: "Professional Photography" },
            { value: "casual photography", name: "Casual Photography" },
            { value: "studio portrait", name: "Studio Portrait (Ring Light)" },
            { value: "fujifilm pro", name: "Fujifilm PRO" },
            { value: "kodak portra", name: "Kodak Portra" },
            { value: "leica m", name: "Leica M-Series" },
            { value: "street photography", name: "Street Photography" },
            { value: "urban exploration", name: "Urban Exploration" },
            { value: "fashion photography", name: "Fashion Editorial" },
            { value: "product photography", name: "Product Photography" },
            { value: "food photography", name: "Food Photography" },
            { value: "macro photography", name: "Macro Photography" },
            { value: "astrophotography", name: "Astrophotography" },
            { value: "underwater", name: "Underwater Photography" },
            { value: "drone photography", name: "Drone Photography" },
            { value: "long exposure", name: "Long Exposure" },
            { value: "tilt-shift", name: "Tilt-Shift" },
            { value: "infrared", name: "Infrared Photography" },
        ],
    },
    {
        label: "Anime & Manga",
        options: [
            { value: "anime", name: "Modern Anime" },
            { value: "studio ghibli", name: "Studio Ghibli" },
            { value: "makoto shinkai", name: "Makoto Shinkai" },
            { value: "90s anime", name: "90s Anime" },
            { value: "manga", name: "Shonen Manga" },
            { value: "seinen manga", name: "Seinen Manga" },
            { value: "webtoon", name: "Webtoon" },
            { value: "manhwa", name: "Korean Manhwa" },
            { value: "chibi", name: "Chibi" },
            { value: "kawaii", name: "Kawaii Style" },
            { value: "mecha anime", name: "Mecha Anime" },
            { value: "shoujo anime", name: "Shoujo Anime" },
        ],
    },
    {
        label: "Digital Painting",
        options: [
            { value: "digital painting", name: "Digital Painting" },
            { value: "concept art", name: "Concept Art" },
            { value: "character design", name: "Character Design" },
            { value: "environment art", name: "Environment Art" },
            { value: "matte painting", name: "Matte Painting" },
            { value: "speedpainting", name: "Speedpainting" },
            { value: "fantasy art", name: "Fantasy Art" },
            { value: "dark fantasy", name: "Dark Fantasy" },
            { value: "book illustration", name: "Book Illustration" },
            { value: "children book", name: "Children's Book" },
        ],
    },
    {
        label: "Traditional Media",
        options: [
            { value: "oil painting", name: "Oil Painting" },
            { value: "watercolor", name: "Watercolor" },
            { value: "gouache", name: "Gouache" },
            { value: "acrylic painting", name: "Acrylic Painting" },
            { value: "pastel", name: "Pastel" },
            { value: "ink wash", name: "Ink Wash" },
            { value: "fresco", name: "Fresco" },
            { value: "tempera", name: "Tempera" },
            { value: "renaissance", name: "Renaissance" },
            { value: "baroque", name: "Baroque" },
            { value: "rococo", name: "Rococo" },
            { value: "impressionist", name: "Impressionist" },
            { value: "post-impressionist", name: "Post-Impressionist" },
            { value: "expressionist", name: "Expressionist" },
            { value: "art nouveau", name: "Art Nouveau" },
            { value: "art deco", name: "Art Deco" },
            { value: "victorian", name: "Victorian" },
            { value: "socialist realism", name: "Socialist Realism" },
        ],
    },
    {
        label: "Drawing Techniques",
        options: [
            { value: "pencil sketch", name: "Pencil Sketch" },
            { value: "charcoal sketch", name: "Charcoal Sketch" },
            { value: "ink drawing", name: "Ink Drawing" },
            { value: "ballpoint pen", name: "Ballpoint Pen" },
            { value: "colored pencil", name: "Colored Pencil" },
            { value: "marker drawing", name: "Marker Drawing" },
            { value: "etching", name: "Etching" },
            { value: "linocut", name: "Linocut" },
            { value: "woodcut", name: "Woodcut" },
            { value: "pointillism", name: "Pointillism" },
            { value: "stippling", name: "Stippling" },
        ],
    },
    {
        label: "3D & CGI",
        options: [
            { value: "3d render", name: "3D Render" },
            { value: "blender", name: "Blender" },
            { value: "unreal engine", name: "Unreal Engine" },
            { value: "octane render", name: "Octane Render" },
            { value: "redshift", name: "Redshift" },
            { value: "arnold render", name: "Arnold Render" },
            { value: "zbrush", name: "ZBrush Sculpt" },
            { value: "claymation", name: "Claymation" },
            { value: "stop motion", name: "Stop Motion" },
            { value: "isometric", name: "Isometric" },
            { value: "voxel art", name: "Voxel Art" },
        ],
    },
    {
        label: "Game Art Styles",
        options: [
            { value: "low poly", name: "Low Poly" },
            { value: "pixel art", name: "Pixel Art" },
            { value: "ps1 graphics", name: "PS1 Graphics" },
            { value: "ps2 graphics", name: "PS2 Graphics" },
            { value: "n64 style", name: "N64 Style" },
            { value: "arc system works", name: "Arc System Works" },
            { value: "cel shaded", name: "Cel-Shaded" },
            { value: "borderlands", name: "Borderlands Style" },
            { value: "valorant style", name: "Valorant Style" },
            { value: "overwatch style", name: "Overwatch Style" },
            { value: "genshin impact", name: "Genshin Impact" },
            { value: "honkai star rail", name: "Honkai: Star Rail" },
        ],
    },
    {
        label: "Cyberpunk & Futuristic",
        options: [
            { value: "cyberpunk", name: "Cyberpunk 2077" },
            { value: "cyberpunk anime", name: "Cyberpunk Anime" },
            { value: "biopunk", name: "Biopunk" },
            { value: "dieselpunk", name: "Dieselpunk" },
            { value: "steampunk", name: "Steampunk" },
            { value: "atompunk", name: "Atompunk" },
            { value: "solarpunk", name: "Solarpunk" },
            { value: "cassette futurism", name: "Cassette Futurism" },
            { value: "retro futurism", name: "Retro Futurism" },
            { value: "blade runner", name: "Blade Runner" },
            { value: "ghost in the shell", name: "Ghost in the Shell" },
        ],
    },
    {
        label: "Cartoon & Comics",
        options: [
            { value: "disney style", name: "Disney" },
            { value: "pixar style", name: "Pixar" },
            { value: "dreamworks", name: "Dreamworks" },
            { value: "cartoon network", name: "Cartoon Network" },
            { value: "adult swim", name: "Adult Swim" },
            { value: "rick and morty", name: "Rick and Morty" },
            { value: "calarts style", name: "CalArts Style" },
            { value: "peanuts", name: "Peanuts" },
            { value: "marvel comics", name: "Marvel Comics" },
            { value: "dc comics", name: "DC Comics" },
            { value: "european comics", name: "European Comics" },
            { value: "french ligne claire", name: "Ligne Claire" },
        ],
    },
    {
        label: "Abstract & Experimental",
        options: [
            { value: "abstract", name: "Abstract" },
            { value: "cubism", name: "Cubism" },
            { value: "surrealism", name: "Surrealism" },
            { value: "dadaism", name: "Dadaism" },
            { value: "bauhaus", name: "Bauhaus" },
            { value: "constructivism", name: "Constructivism" },
            { value: "psychedelic", name: "Psychedelic" },
            { value: "fluid art", name: "Fluid Art" },
            { value: "glitch art", name: "Glitch Art" },
            { value: "fractal art", name: "Fractal Art" },
            { value: "generative art", name: "Generative Art" },
            { value: "data bending", name: "Data Bending" },
        ],
    },
    {
        label: "Special Effects",
        options: [
            { value: "holographic", name: "Holographic" },
            { value: "neon glow", name: "Neon Glow" },
            { value: "chromatic aberration", name: "Chromatic Aberration" },
            { value: "double exposure", name: "Double Exposure" },
            { value: "light painting", name: "Light Painting" },
            { value: "lens flare", name: "Lens Flare" },
            { value: "vhs effect", name: "VHS Effect" },
            { value: "crt screen", name: "CRT Screen" },
            { value: "film grain", name: "Film Grain" },
            { value: "cross processing", name: "Cross Processing" },
        ],
    },
    {
        label: "Cultural & Historical",
        options: [
            { value: "ukiyo-e", name: "Ukiyo-e" },
            { value: "chinese painting", name: "Chinese Painting" },
            { value: "sumi-e", name: "Sumi-e" },
            { value: "persian miniature", name: "Persian Miniature" },
            { value: "medieval illuminated", name: "Medieval Illuminated" },
            { value: "byzantine icon", name: "Byzantine Icon" },
            { value: "tribal art", name: "Tribal Art" },
            { value: "afrofuturism", name: "Afrofuturism" },
            { value: "indigenous art", name: "Indigenous Art" },
            { value: "soviet propaganda", name: "Soviet Propaganda" },
        ],
    },
];